export const data = [
  {
    id: 1,
    name: "",
    rooms: "3",
    bed: "2",
    bath: "1",
    square_ft: "725",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8266",
    Address: "",
    city: "New York",
  },
  {
    id: 2,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "732",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "82555",
    Address: "",
    city: "New York",
  },
  {
    id: 3,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "867",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "7899",
    Address: "",
    city: "New York",
  },
  {
    id: 4,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "814",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "6,255",
    location: "8266",
    Address: "",
    city: "New York",
  },
  {
    id: 5,
    name: "",
    rooms: "4",
    bed: "4",
    bath: "1",
    square_ft: "856",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "6,255",
    location: "8266",
    Address: "",
    city: "New York",
  },
  {
    id: 6,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "876",
    isPopular: true,
    status: "sale",
    image: "",
    rent: "8,255",
    location: "8266",
    Address: "",
    city: "New York",
  },
  {
    id: 7,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "890",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8266",
    Address: "",
    city: "New York",
  },
  {
    id: 8,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "877",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "4,255",
    location: "8765",
    Address: "",
    city: "New York",
  },
  {
    id: 9,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "843",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "6,255",
    location: "6788",
    Address: "",
    city: "New York",
  },
  {
    id: 10,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "890",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "4,555",
    location: "8909",
    Address: "",
    city: "New York",
  },
  {
    id: 11,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "567",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "78999",
    Address: "",
    city: "New York",
  },
  {
    id: 12,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "756",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "8,255",
    location: "76788",
    Address: "",
    city: "New York",
  },
  {
    id: 13,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,789",
    location: "6578",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 14,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "890",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "7,345",
    location: "2637",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 15,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "4,567",
    location: "8999",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 16,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "7,355",
    location: "6789",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 17,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "890",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "8,567",
    location: "8799",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 18,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: true,
    status: "sale",
    image: "",
    rent: "8,567",
    location: "7889",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 19,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "6,789",
    location: "45678",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 20,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "7899",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 21,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8799",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 22,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8799",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 23,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "8799",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 24,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "456",
    isPopular: true,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "7899",
    Address: "",
    city: "Mumbai",
  },
  {
    id: 25,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "6788",
    Address: "",
    city: "Paris",
  },
  {
    id: 26,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "8900",
    Address: "",
    city: "Paris",
  },
  {
    id: 27,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: true,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "78999",
    Address: "",
    city: "Paris",
  },
  {
    id: 28,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "890",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "89776",
    Address: "",
    city: "Paris",
  },
  {
    id: 29,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "7899",
    Address: "",
    city: "London",
  },
  {
    id: 30,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8977",
    Address: "",
    city: "Paris",
  },
  {
    id: 31,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: true,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8976",
    Address: "",
    city: "Paris",
  },
  {
    id: 32,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "567",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "8799",
    Address: "",
    city: "Paris",
  },
  {
    id: 33,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "6789",
    Address: "",
    city: "Paris",
  },
  {
    id: 34,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "567",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "Paris",
  },
  {
    id: 35,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "7897",
    Address: "",
    city: "Paris",
  },
  {
    id: 36,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "Paris",
  },
  {
    id: 37,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "Paris",
  },
  {
    id: 38,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "London",
  },
  {
    id: 39,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "London",
  },
  {
    id: 40,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "London",
  },
  {
    id: 41,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "London",
  },
  {
    id: 42,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "London",
  },
  {
    id: 43,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "London",
  },
  {
    id: 44,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "London",
  },
  {
    id: 45,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "London",
  },
  {
    id: 46,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "London",
  },
  {
    id: 36,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "London",
  },
  {
    id: 36,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "",
    city: "London",
  },
];

export default data;
