export const data = [
  {
    id: 1,
    name: "",
    rooms: "3",
    bed: "2",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 2,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 3,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 4,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "6,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 5,
    name: "",
    rooms: "4",
    bed: "4",
    bath: "1",
    square_ft: "",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "6,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 6,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: true,
    status: "sale",
    image: "",
    rent: "8,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 7,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 8,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 9,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 10,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 11,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 12,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 13,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 14,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 15,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 16,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 17,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 18,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 19,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 20,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 21,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 22,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 23,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 24,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 25,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 26,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 27,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 28,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 29,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 30,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 31,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 32,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 33,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 34,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 35,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
  {
    id: 36,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "",
    Address: "",
    city: "New York",
  },
];

export default data;
