export const data = [
  {
    id: 1,
    name: "",
    rooms: "3",
    bed: "2",
    bath: "1",
    square_ft: "725",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8266",
    Address: "47 W 13th St, New York, NY 10011",
    city: "New York",
  },
  {
    id: 2,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "732",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "82555",
    Address: "20 Cooper Square, New York, NY 10003",
    city: "New York",
  },
  {
    id: 3,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "867",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "7899",
    Address: "1 E 2nd St, New York, NY 10003",
    city: "New York",
  },
  {
    id: 4,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "814",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "6,255",
    location: "8266",
    Address: "75 3rd Ave, New York, NY 10003",
    city: "New York",
  },
  {
    id: 5,
    name: "",
    rooms: "4",
    bed: "4",
    bath: "1",
    square_ft: "856",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "6,255",
    location: "8266",
    Address: "Metrotech Center, Brooklyn, NY 11201",
    city: "New York",
  },
  {
    id: 6,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "876",
    isPopular: true,
    status: "sale",
    image: "",
    rent: "8,255",
    location: "8266",
    Address: "721 Broadway, New York, NY 10003",
    city: "New York",
  },
  {
    id: 7,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "890",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8266",
    Address: "40 E 7th St, New York, NY 10003",
    city: "New York",
  },
  {
    id: 8,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "877",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "4,255",
    location: "8765",
    Address: "838 Broadway, New York, NY 10003",
    city: "New York",
  },
  {
    id: 9,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "843",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "6,255",
    location: "6788",
    Address: "69 W 9th St, New York, NY 10011",
    city: "New York",
  },
  {
    id: 10,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "890",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "4,555",
    location: "8909",
    Address: "19 Washington Square N, New York, NY 10011",
    city: "New York",
  },
  {
    id: 11,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "567",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "78999",
    Address: "371 7th Ave, New York, NY 10001",
    city: "New York",
  },
  {
    id: 12,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "756",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "8,255",
    location: "76788",
    Address: "33 3rd Ave, New York, NY 10003",
    city: "New York",
  },
  {
    id: 13,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "7,789",
    location: "6578",
    Address: "Residential House Kanjurmarg East",
    city: "Mumbai",
  },
  {
    id: 14,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "890",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "7,345",
    location: "2637",
    Address: "Evershine dream park",
    city: "Mumbai",
  },
 
  {
    id: 15,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "4,567",
    location: "8999",
    Address: "Sanjay Gandhi national park",
    city: "Mumbai",
  },
  {
    id: 16,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "7,355",
    location: "6789",
    Address: " Gurudev Ravindranath Tagore Udyan",
    city: "Mumbai",
  },
  {
    id: 17,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "890",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "8,567",
    location: "8799",
    Address: " Thane Mahanagar Palika",
    city: "Mumbai",
  },
  {
    id: 18,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: true,
    status: "sale",
    image: "",
    rent: "8,567",
    location: "7889",
    Address: "Hiranandani Castle Rock",
    city: "Mumbai",
  },
  {
    id: 19,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "6,789",
    location: "45678",
    Address: "Sheth Vasant Oasis",
    city: "Mumbai",
  },
  {
    id: 20,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "7899",
    Address: "Oberoi Realty Enigma and Eternia",
    city: "Mumbai",
  },
  {
    id: 21,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8799",
    Address: "Aristo Pearl Residency",
    city: "Mumbai",
  },
  {
    id: 22,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8799",
    Address: "Blue Bell Chembur",
    city: "Mumbai",
  },
  {
    id: 23,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "8799",
    Address: "Dosti Group Flamingos",
    city: "Mumbai",
  },
  {
    id: 24,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "456",
    isPopular: true,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "7899",
    Address: "Kshitija Shree Laxmi Residency",
    city: "Mumbai",
  },
  {
    id: 25,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "6788",
    Address: "Avenue des Champs-Élysées",
    city: "Paris",
  },
  {
    id: 26,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: true,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "8900",
    Address: "Avenue Victor Hugo",
    city: "Paris",
  },
  {
    id: 27,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: true,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "78999",
    Address: "Avenue Montaigne",
    city: "Paris",
  },
  {
    id: 28,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "890",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "89776",
    Address: "Rue de Rivoli",
    city: "Paris",
  },
  {
    id: 29,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "7899",
    Address: "Rue Saint-Rustique",
    city: "London",
  },
  {
    id: 30,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8977",
    Address: "Rue Montorgueil",
    city: "Paris",
  },
  {
    id: 31,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: true,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8976",
    Address: "Rue Saint-Dominique",
    city: "Paris",
  },
  {
    id: 32,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "567",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "8799",
    Address: "Rue Oberkampf",
    city: "Paris",
  },
  {
    id: 33,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "789",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "6789",
    Address: "Rue Vieille du Temple",
    city: "Paris",
  },
  {
    id: 34,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "567",
    isPopular: false,
    status: "rent",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "Rue des Francs-Bourgeois",
    city: "Paris",
  },
  {
    id: 35,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "7897",
    Address: "Cruise on the Seine",
    city: "Paris",
  },
  {
    id: 36,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "Palace of Versailles",
    city: "Paris",
  },
  {
    id: 37,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "Cruise on the Seine",
    city: "Paris",
  },
  {
    id: 38,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "London Eye",
    city: "London",
  },
  {
    id: 39,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "Warner Bros. Studio Tour London",
    city: "London",
  },
  {
    id: 40,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "Madame Tussauds London",
    city: "London",
  },
  {
    id: 41,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "Westminster Abbey ",
    city: "London",
  },
  {
    id: 42,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "Piccadilly Circus And Trafalgar Square",
    city: "London",
  },
  {
    id: 43,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "The Victoria And Albert Museum ",
    city: "London",
  },
  {
    id: 44,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "Notting Hill Gate",
    city: "London",
  },
  {
    id: 45,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "Buckingham Palace",
    city: "London",
  },
  {
    id: 46,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "The British Museum",
    city: "London",
  },
  {
    id: 47,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "Covent Garden",
    city: "London",
  },
  {
    id: 48,
    name: "",
    rooms: "4",
    bed: "3",
    bath: "1",
    square_ft: "678",
    isPopular: false,
    status: "sale",
    image: "",
    rent: "7,255",
    location: "8769",
    Address: "Hampton Court Palace",
    city: "London",
  },
  
];

export default data;
